### ISSUE TITLE
Changing format for Lastkajen data

### ISSUE THREAD

**Issue by matthiasfeist** [atorger/nvdb2osm#48]
Hi.
I just got an email from Trafikverket to all Lastkajen users. It seems that they are discontinuing the shape files and will only provide GeoDB or Geopkg files by the end of the year...

**Comment by atorger** [comment]
Sigh... they have been really good at keeping us busy with their frequent changes. This is a pretty big change, but in the long term it's probably to the better. Shape files is a pretty old-school format. I don't remember why I chose that format when I start making the script in the first place, but I think it was something with the good availability of open source tools/libraries.

Anyway, there's a few months left of shape files so I'll probably look into this some time after shape files actually disappear, this autumn or winter. Or if I get bored during summer. I'm really bad at planning :-).

**Comment by matthiasfeist** [comment]
Haha yes I know. 
Well, I just wanted to bring this to your attention.
Maybe a good step could be to use a tool like ogr2ogr to convert the files to shape. But I'd assume even then there will be quite a lot of changes to be made in the script

**Comment by atorger** [comment]
Yes I'll look into what ogr2ogr can do as a first step, it may be the easiest way out. Could maybe call it automatically from the script so it would be transparent to the user. I would expect some issues with key/value names and content but I'll see. If there is a lot of issues it's probably better to try using the GeoDB format directly.

Geopkg is all layers already merged format I think, which is kind of good as much of my script and issues is around merging. However, there is an advantage of doing the merging of layers oneself too though as there is some content-aware "smartness" there to take care of corner cases, so I think I'll stick with GeoDB and separate layers approach.

**Comment by atorger** [comment]
The split script now accepts both shapefile and geopackage, and will always output geopackage, which then nvdb2osm works with.

There are some issues with date parsing logs at splitting but one can ignore those, it's just a lot of zero dates which fiona complains about. I had to add some more values of "undefined" as empty strings turned up instead of None here and there.

So now it should work with geopackage, but there could be some quirks left.

Trafikverket also seems to be changing some column names later on which they have not done yet, so there will have to be some adjustment later too.

**Comment by matthiasfeist** [comment]
cool. I'll take a look if I could adjust the pipeline to download the geopackages

**Comment by matthiasfeist** [comment]
I just tried it (with the latest version on master) but I get this error and then the splitting script halts:

```
2022-07-03 13:40:34,010 - split_nvdb_data - INFO - Saving NVDB-Antal_korfalt2.gkpg for Ockelbo
2022-07-03 13:40:34,046 - split_nvdb_data - INFO - Saving NVDB-Antal_korfalt2.gkpg for Nordanstig
2022-07-03 13:40:34,123 - split_nvdb_data - INFO - Saving NVDB-Antal_korfalt2.gkpg for Hofors
2022-07-03 13:40:34,158 - split_nvdb_data - INFO - Reading layer NVDB*Barighet (6 of 47 layers) from ../download/21.zip
2022-07-03 13:40:34,159 - split_nvdb_data - INFO - Reading layer Gävleborgs_län_Shape_NVDB_DK_O_10_Barighet from file zip://../download/21.zip!Gävleborgs_län.gpkg
Traceback (most recent call last):
  File "fiona/ogrext.pyx", line 271, in fiona.ogrext.FeatureBuilder.build
ValueError: year 0 is out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/matthiasf/src/nvdb2osm-pipeline/workdir/nvdb2osm/split_nvdb_data.py", line 295, in <module>
    main()
  File "/Users/matthiasf/src/nvdb2osm-pipeline/workdir/nvdb2osm/split_nvdb_data.py", line 240, in main
    gdf = read_gpkg_layer(geometry_file, ln)
  File "/Users/matthiasf/src/nvdb2osm-pipeline/workdir/nvdb2osm/split_nvdb_data.py", line 73, in read_gpkg_layer
    gdf = geopandas.read_file(filename, encoding='cp1252', layer=layer_name)
  File "/Users/matthiasf/src/nvdb2osm-pipeline/python-env/lib/python3.9/site-packages/geopandas/io/file.py", line 139, in _read_file
    return GeoDataFrame.from_features(
  File "/Users/matthiasf/src/nvdb2osm-pipeline/python-env/lib/python3.9/site-packages/geopandas/geodataframe.py", line 422, in from_features
    for feature in features_lst:
  File "fiona/ogrext.pyx", line 1515, in fiona.ogrext.Iterator.__next__
  File "fiona/ogrext.pyx", line 277, in fiona.ogrext.FeatureBuilder.build
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1481, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1598, in handle
    if (not self.disabled) and self.filter(record):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 806, in filter
    result = f.filter(record)
  File "/Users/matthiasf/src/nvdb2osm-pipeline/python-env/lib/python3.9/site-packages/fiona/logutils.py", line 18, in filter
    if getattr(record, 'msg', "").startswith("Skipping field"):
AttributeError: 'ValueError' object has no attribute 'startswith'
```

**Comment by atorger** [comment]
ValueError: year 0 is out of range is normal due to that NVDB has lots of dates set to zero and the fiona library that reads geopackage files doesn't like that. However, it should be okay to ignore those errors. What seems to go wrong there is something with logutils.py handling that error... strange that I didn't get that, probably due to that I have some different version of the fiona library.

**Comment by atorger** [comment]
There a few ways to fix the ValueError problem so it does not show at all is to 1) make trafikverket provide sane date values, 2) make fiona maintainers accept 0 as a valid date, or 3) write an own geopackage reader (which actually is not that hard as geopackage files are pure sqlite3 databases).

However as it works for me despite those ugly logs I have ignored it for now... 

(I think fiona is part of the geopandas package so if fiona is not installed separately you can try to upgrade geopandas)

**Comment by matthiasfeist** [comment]
Hmmm... I don't install anything myself but only use the requirements.txt file in your repo to install dependencies. Does that mean you need to update this file to reflect the newest versions?

**Comment by atorger** [comment]
hmm yeah maybe, actually it's not me that made the requirements.txt that was some python guru which contributed some patches early on. I have installed my packages manually before that and I have 0.11.0 installed, the requirement files say 0.8.2 maybe that's bad...

**Comment by atorger** [comment]
I pushed a new requirements file.

If already installed it seems like this works:

pip install --upgrade -r requirements.txt

otherwise a fresh install should work, then it should get the latest geopandas hopefully

**Comment by matthiasfeist** [comment]
now I get a new error that I haven't seen before.
I completely installed all dependencies from scratch with your new requirements file.
I think it would be best to really specify the exact library versions there that you use as well (I _think_ currently you are specifying only that e.g. geopandas should be at the latest version, not the exact version you want).

here's the error:

```
python split_nvdb_data.py --lanskod_filter 17 ../download/17.zip output/
2022-07-04 08:55:15,141 - split_nvdb_data - INFO - args are Namespace(geo_file=PosixPath('../download/17.zip'), output_dir=PosixPath('output'), lanskod_filter='17', loglevel=30)
2022-07-04 08:55:15,141 - split_nvdb_data - INFO - Checksum for each script file (to be replaced with single version number when script is stable):
2022-07-04 08:55:15,142 - split_nvdb_data - INFO -   split_nvdb_data.py     MD5: e2eeaa228f028e6769ea92bb631e944e
2022-07-04 08:55:15,142 - split_nvdb_data - INFO - Loading municipality borders
2022-07-04 08:55:15,144 - split_nvdb_data - INFO - Reading file ak_riks.shp
Traceback (most recent call last):
  File "/Users/matthiasf/src/nvdb2osm-pipeline/workdir/nvdb2osm/split_nvdb_data.py", line 295, in <module>
    main()
  File "/Users/matthiasf/src/nvdb2osm-pipeline/workdir/nvdb2osm/split_nvdb_data.py", line 224, in main
    municipalities = load_municipalities(lanskod)
  File "/Users/matthiasf/src/nvdb2osm-pipeline/workdir/nvdb2osm/split_nvdb_data.py", line 129, in load_municipalities
    gdf = read_epsg_shapefile("data/ak_riks.zip", "ak_riks")
  File "/Users/matthiasf/src/nvdb2osm-pipeline/workdir/nvdb2osm/split_nvdb_data.py", line 109, in read_epsg_shapefile
    gdf = geopandas.read_file(gdf_filename, encoding='cp1252')
  File "/Users/matthiasf/src/nvdb2osm-pipeline/python-env/lib/python3.9/site-packages/geopandas/io/file.py", line 253, in _read_file
    return _read_file_fiona(
  File "/Users/matthiasf/src/nvdb2osm-pipeline/python-env/lib/python3.9/site-packages/geopandas/io/file.py", line 340, in _read_file_fiona
    df = GeoDataFrame.from_features(
  File "/Users/matthiasf/src/nvdb2osm-pipeline/python-env/lib/python3.9/site-packages/geopandas/geodataframe.py", line 652, in from_features
    return cls(rows, columns=columns, crs=crs)
  File "/Users/matthiasf/src/nvdb2osm-pipeline/python-env/lib/python3.9/site-packages/geopandas/geodataframe.py", line 170, in __init__
    self["geometry"] = _ensure_geometry(self["geometry"].values, crs)
  File "/Users/matthiasf/src/nvdb2osm-pipeline/python-env/lib/python3.9/site-packages/geopandas/geodataframe.py", line 62, in _ensure_geometry
    out = from_shapely(data, crs=crs)
  File "/Users/matthiasf/src/nvdb2osm-pipeline/python-env/lib/python3.9/site-packages/geopandas/array.py", line 150, in from_shapely
    return GeometryArray(vectorized.from_shapely(data), crs=crs)
  File "/Users/matthiasf/src/nvdb2osm-pipeline/python-env/lib/python3.9/site-packages/geopandas/_vectorized.py", line 146, in from_shapely
    aout[:] = out
  File "/Users/matthiasf/src/nvdb2osm-pipeline/python-env/lib/python3.9/site-packages/shapely/geometry/polygon.py", line 300, in __array_interface__
    raise NotImplementedError(
NotImplementedError: A polygon does not itself provide the array interface. Its rings do.
```

**Comment by matthiasfeist** [comment]
Same error with 0.11.0... I wonder if it's maybe a different library that needs bumping?

**Comment by atorger** [comment]
Oh, "site-packages/shapely/geometry/polygon.py", seems to point to Shapely. Maybe try shapely 1.8.2

**Comment by matthiasfeist** [comment]
can you maybe update the requirements.txt file with the exact versions that you use locally on your machine?

**Comment by atorger** [comment]
Requirement already satisfied: Shapely>=1.7.1 in /home/anders/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.8.2)
Requirement already satisfied: sortedcontainers>=2.1.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: geopandas>=0.8.2 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (0.11.0)
Requirement already satisfied: scanf>=1.5.2 in /home/anders/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (1.5.2)
Requirement already satisfied: pyproj>=3.0.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (3.3.1)

The column to the right is the versions I'm using. I run a bleeding edge system and get new versions all the time, I don't really want to put higher version numbers there than actually required. Could be some other python environment issue too.

**Comment by atorger** [comment]
That is
Shapely>=1.8.2
sortedcontainers>=2.4.0
geopandas>=0.11.0
scanf>=1.5.2
pyproj>=3.3.1

I don't think requirements includes "default" dependencies though. I run with Python version 3.10.5

**Comment by matthiasfeist** [comment]
OK that worked now (at least the split script). So maybe commit these dependencies into the repo?

**Comment by atorger** [comment]
Yeah I pushed it now

**Comment by marsip** [comment]
I have updated my java build environment in Windows 10 PC and can now successfully build osmfiles. Before the update my old environment (for shp-files) didn't work.


I followed the installs instructions in:
https://geoffboeing.com/2014/09/using-geopandas-windows/

My packages:

Package          Version
---------------- ---------
attrs            21.4.0
certifi          2021.10.8
click            8.0.3
click-plugins    1.1.1
cligj            0.7.2
colorama         0.4.4
Fiona            1.8.21
GDAL             3.4.3
geopandas        0.12.1
munch            2.5.0
numpy            1.22.2
packaging        21.3
pandas           1.4.0
pip              22.3
pyparsing        3.0.9
pyproj           3.3.1
python-dateutil  2.8.2
pytz             2021.3
Rtree            1.0.0
scanf            1.5.2
Shapely          1.8.2
six              1.16.0
sortedcontainers 2.4.0

java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

**Comment by matthiasfeist** [comment]
Thanks. In the cloud environment which runs nvdb2osm, I automatically create the python environment using the requirements.txt file. So we need to make sure that this file reflects all the correct versions of all dependencies.
Have a look here about how to generate a complete file: https://learnpython.com/blog/python-requirements-file/

**Comment by atorger** [comment]
My pip3 freeze list outputs more than 200 packets, so I don't think it makes that much sense. I have a very rich python environment as lots of the system uses Python, not just this script. I don't know much about setting up python environments from a Configuration Management perspective as for me so far it has "always worked". I use Debian Linux where the python packets installed are a mix of system wide installation and per user local installation.

**Comment by matthiasfeist** [comment]
Haha ok that's a long list and I agree that it doesn't make sense to include all of this I'm the requirements file. But somehow I need to have a way to reliably replicate the environment you're running with some sort of machine readable specifications you provide.

**Comment by matthiasfeist** [comment]
I know a little bit about python programming and generally it's best practice to have a dedicated virtual environment to avoid the situation that you have right now where it's unclear which dependencies the script really has and which other packages that are installed have a unknown effect on the code.

See here for example: https://blog.inedo.com/python-environment-management-best-practices

**Comment by marsip** [comment]
The list of dependencies I showed, are the only I have in my Phyton environment. 
(Besides any hidden dependences the basic Phyton environment maybe have).

It should be enough to have these for a successful build.

**Comment by matthiasfeist** [comment]
Can you try maybe something like this: https://github.com/bndr/pipreqs

the thing is that it's really important that the requirements.txt file is correct and up-to-date if we want this project to work reliably on other people's computers and in the cloud.

**Comment by anders-xarepo** [comment]
Did that and committed/pushed the new requirements.txt, this was the result:

Fiona==1.8.21
geopandas==0.11.1
pyproj==3.4.0
scanf==1.5.2
Shapely==1.8.5
sortedcontainers==2.4.0

(logged in with my work user to lazy to change...)

**Comment by matthiasfeist** [comment]
So I finally had time to look at this. It was not easy to just test it as Trafikverket had again changed their API so I needed to adjust my scripts as well to be able to download the files.

I've processed now Östergötlands län on the cloud infrastructure (random choice, I know 😆) with the new requirements.txt file that is commited in the repo.

it seems to me that now the splitting of the files is randomly breaking. here's the split logfile for the run: https://nvdb-osm-map-data.s3.eu-north-1.amazonaws.com/split/split_5.log there's a lot of random warnings from Fiona...

**Comment by marsip** [comment]
I also get lot of errors on splitting with my local build environment (windows 10), but the splitting doesn't abort/exit and the result files are ok. But I have only tested Västernorrlands län.

**Comment by matthiasfeist** [comment]
I'm currently testing if the amount of errors generates too large log files. I'm saving all the log output so it's possible to debug it. But since Fiona seems to log like crazy some logfiles are getting about 100MB or larger ...

**Comment by elindberg-snapcode** [comment]
I'm brining this thread back to life since there seems to be some issues with splitting the geo package file (split_nvdb_data).
Hopefully, I'm missing something but I've tried everything I can think of so next step is to try a post here :)
I can successfully split the old shape files (I had an old one lying around), but when trying the new geo package format I end up with an RLID error of some kind. 

"geometry with RLID {row.RLID} not contained nor intersecting with any municipality"

The entire error message is as follows:
`2023-04-27 12:17:59,851 - split_nvdb_data - INFO - Reading layer NVDB_DK_O_38_FunkVagklass from file zip://../Vasternorrland_GeoPackage.zip!Västernorrlands_län.gpkg`
`2023-04-27 12:18:21,935 - split_nvdb_data - INFO - done (93779 segments)`
`Traceback (most recent call last):`
`  File "./split_nvdb_data.py", line 295, in <module>
    main()`
`  File "./split_nvdb_data.py", line 269, in main`
`    _log.info(f"geometry with RLID {row.RLID} not contained nor intersecting with any municipality")`
`  File "/home/likj8457/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)`
`AttributeError: 'Series' object has no attribute 'RLID'`

Since Västernorrland was working 5 months ago, I tried to find out if something has happened to the format. And sure enough, it has. I cant say this is the problem... but for someone with insight in the scripts.. it might be a starting point?
![image](https://user-images.githubusercontent.com/103041861/234836127-a2a95aa5-8b68-4f8c-8264-f4a570f0d5a4.png)

Any Ideas?

**Comment by atorger** [comment]
I'll probably need to change the code again. Trafikverket have had quite a good number of format changes over the past couple of years, some small some large, so nvdb2osm breaks now and then. It's usually quite easy for me to adapt the code to the new format but I need to get time to look into it, and for the moment I have a bit much stuff to do.

**Comment by atorger** [comment]
Started to look at it, seems like Trafikverket has changed the names of basically all tags... I guess it's good in the long term though, as now they use proper timestamps and tag names that aren't truncated. But there's a lot stuff that needs to be changed in the huge script. I'll probably do the easier way first and just translate new tags back to old names, less risk of introducing errors. Then when things settle down a bit one can ditch support for the old abbreviated tag names.

**Comment by atorger** [comment]
I have now pushed some patches so it should work again on new NVDB dumps, should still work for the old. It's more than 500 lines of new code, but mostly just tag translations. To make minimum impact on existing code to minimize risk of introducing errors, I'm converting new key names back to the old, but in the long term it would be nice to convert all code to use new full length names, makes the code easier to read and understand.

Apart from changing the names of all keys in all databases, they have also changed some value types so I needed to patch a  bit extra for that. Let me know if you run into any problems, I have only done some brief tests on Västernorrland data.

**Comment by elindberg-snapcode** [comment]
Seems like it did the trick!
I just ran Södermanland without any errors, thanks!
